import type { AtlasView, BodyViewId } from './types';

/**
 * The project's own schematic body figure.
 *
 * This is a deliberately abstract mannequin drawn from simple strokes. It is a
 * spatial-memory scaffold, NOT an anatomical illustration, and the UI says so.
 * No external, licensed, traced or AI-generated body art is used anywhere.
 */

export const ATLAS_WIDTH = 400;
/**
 * Canvas height is set so the figure sits vertically centred: the drawn body
 * spans y 35..888, which leaves ~35 px of air above the crown and below the
 * toes. Placements are stored normalised, so changing this re-frames the view
 * without moving a single marker relative to the body.
 */
export const ATLAS_HEIGHT = 924;

export const atlasViews: AtlasView[] = [
  { id: 'front', labelEn: 'Front', labelZh: '前面', width: ATLAS_WIDTH, height: ATLAS_HEIGHT },
  { id: 'back', labelEn: 'Back', labelZh: '背面', width: ATLAS_WIDTH, height: ATLAS_HEIGHT },
];

/** Convert schematic pixel coordinates to normalised 0..1 atlas space. */
export const norm = (x: number, y: number) => ({ x: x / ATLAS_WIDTH, y: y / ATLAS_HEIGHT });

/** Convert normalised coordinates back to schematic user space. */
export const denorm = (x: number, y: number) => ({ x: x * ATLAS_WIDTH, y: y * ATLAS_HEIGHT });

export interface FigureShape {
  kind: 'circle' | 'path' | 'stroke';
  d?: string;
  cx?: number;
  cy?: number;
  r?: number;
  strokeWidth?: number;
}

/**
 * Build a smooth, tapered limb silhouette around a centre-line.
 *
 * The outline is generated by offsetting each centre-line vertex along its
 * normal by a per-vertex half-width, adding rounded end caps, and running the
 * whole ring through the Catmull-Rom smoother. Because the input IS the limb
 * guide the markers anchor to, the drawing can never drift away from the data.
 */
export function limbOutline(
  pts: readonly (readonly [number, number])[],
  halfWidths: readonly number[],
): string {
  if (pts.length < 2 || pts.length !== halfWidths.length) return '';
  const dirs = pts.map((_, i) => {
    const a = pts[Math.max(0, i - 1)]!;
    const b = pts[Math.min(pts.length - 1, i + 1)]!;
    const dx = b[0] - a[0];
    const dy = b[1] - a[1];
    const len = Math.hypot(dx, dy) || 1;
    return { x: dx / len, y: dy / len };
  });
  const left = pts.map((p, i) => ({
    x: p[0] - dirs[i]!.y * halfWidths[i]!,
    y: p[1] + dirs[i]!.x * halfWidths[i]!,
  }));
  const right = pts.map((p, i) => ({
    x: p[0] + dirs[i]!.y * halfWidths[i]!,
    y: p[1] - dirs[i]!.x * halfWidths[i]!,
  }));
  const first = pts[0]!;
  const last = pts[pts.length - 1]!;
  const startCap = {
    x: first[0] - dirs[0]!.x * halfWidths[0]! * 0.9,
    y: first[1] - dirs[0]!.y * halfWidths[0]! * 0.9,
  };
  const endCap = {
    x: last[0] + dirs[dirs.length - 1]!.x * halfWidths[halfWidths.length - 1]! * 0.9,
    y: last[1] + dirs[dirs.length - 1]!.y * halfWidths[halfWidths.length - 1]! * 0.9,
  };
  return `${smoothPath([startCap, ...left, endCap, ...[...right].reverse()])} Z`;
}

/* -------------------------------------------------------------------------- *
 * Figure geometry — 7.5-head mannequin.
 *
 * Owner spec (2026-08-06 concept round, Option 1 with refinements): a
 * volumetric mannequin at the standard 7.5-head canon, with a readable face,
 * visible elbow and knee contours, and fully articulated hands and feet.
 * The face is deliberate, not decoration: ST1–ST8 and LI19/LI20 are defined
 * against the eye, nose, mouth and jaw, so those features are the referents
 * the learner needs. Digits are articulated for the same reason — 合谷 sits in
 * the thumb web, 少商 on the thumbnail, 商陽 on the index nail.
 *
 * Everything derives from PROPORTIONS below, so the whole figure can be
 * re-tuned by editing a handful of numbers rather than a wall of path data.
 * The figure stays an ethnically neutral schematic; it is not an anatomical
 * reference and every marker remains `schematic_unvalidated`.
 * -------------------------------------------------------------------------- */

/** One head height. The canon: 7.5 of these from crown to sole. */
export const HEAD_UNIT = 111;
const CROWN = 35;
const MID = ATLAS_WIDTH / 2;
const hu = (n: number) => CROWN + n * HEAD_UNIT;

/** Vertical anatomy, in head units from the crown. */
export const LEVELS = {
  crown: CROWN,
  eye: hu(0.52),
  nose: hu(0.72),
  mouth: hu(0.85),
  chin: hu(1.0),
  neckBase: hu(1.28),
  shoulder: hu(1.53),
  nipple: hu(2.05),
  navel: hu(3.0),
  crotch: hu(4.0),
  elbow: hu(3.04),
  wrist: hu(4.2),
  knee: hu(5.6),
  ankle: hu(7.2),
  sole: hu(7.5),
} as const;

/**
 * Limb centre-lines: shoulder → elbow → wrist, hip → knee → ankle.
 * Arms are slightly abducted so the arm channels clear the trunk channels.
 */
export const LIMB_GUIDES = {
  /** Person's right arm (drawn on the viewer's left). */
  armRight: [
    [128, LEVELS.shoulder],
    [82, LEVELS.elbow],
    [70, LEVELS.wrist],
  ],
  /** Person's left arm (drawn on the viewer's right). */
  armLeft: [
    [272, LEVELS.shoulder],
    [318, LEVELS.elbow],
    [330, LEVELS.wrist],
  ],
  legRight: [
    [168, LEVELS.crotch + 6],
    [160, LEVELS.knee],
    [154, LEVELS.ankle],
  ],
  legLeft: [
    [232, LEVELS.crotch + 6],
    [240, LEVELS.knee],
    [246, LEVELS.ankle],
  ],
} as const;

/**
 * Back-view vertebral ladder.
 *
 * The back-shu points are located BY vertebral level ("below the spinous
 * process of T3, 1.5 cun lateral"), so the figure needs that ladder as real
 * coordinates rather than eyeballed dots.
 *
 * The whole ladder is one measurement now, hung between the two features of
 * this figure that a spine actually has to fit between: the drawn C7 at the
 * neck base, and the drawn coccyx tip. Both come from the HRA reference spine
 * (CC BY 4.0 — cited on the About page, and surveyed in
 * content-review/3d-asset-survey-2026-08-22.md).
 *
 * WHY NOT A CHOSEN STEP: the ladder used to step 13.6 px through the thoracic
 * spine and 14 px through the lumbar — a ratio of 1.029, where the reference
 * spine gives 1.225, and a thoracic step so coarse that all 23.6 levels needed
 * 321 px of trunk when only 290 px exist. It could not close, so the sacrum
 * absorbed the difference and 八髎 sat about 12% too tight.
 *
 * The drawn figure was NOT the problem and has not been touched: C7 to coccyx
 * tip is 34.83% of this figure's height against the model's 34.53%, right to
 * 0.30%. Only the step inside that span was wrong.
 *
 * WHAT THE NAVEL COSTS: L2 no longer lands exactly on it. The owner's worksheet
 * states 「與臍相平」 for 命門 GV4 and this ladder puts the navel about half a
 * lumbar interval below L2 — closer to L2/L3, where modern anatomy generally
 * puts it too. Owner's decision, 2026-08-22: the anatomical ladder wins and the
 * teaching text is reviewed separately.
 */
const LADDER_TOP = LEVELS.neckBase + 9;
const COCCYX_Y = 476;

/*
 * The reference spine, as metres below its own C7 spinous process. The two
 * steps are least-squares fits through its spinous tips; the C7→T1 and
 * C7→coccyx offsets are measured directly. Uniform steps rather than the
 * model's per-level gaps — the fit's residual is 0.13 of a level, so the
 * individual gaps are one body's noise and copying them would be overfitting.
 */
const M_C7_T1 = 0.0205;
const M_T_STEP = 0.02676;
const M_L_STEP = 0.0328;
const M_C7_COCCYX = 0.6317;

/** One scale, so the ladder closes on the drawn coccyx tip by construction. */
const PX_PER_M = (COCCYX_Y - LADDER_TOP) / M_C7_COCCYX;
const T_STEP = M_T_STEP * PX_PER_M;
const L_STEP = M_L_STEP * PX_PER_M;
const T1_Y = LADDER_TOP + M_C7_T1 * PX_PER_M;
const T12_Y = T1_Y + 11 * T_STEP;
const L5_Y = T12_Y + 5 * L_STEP;
/**
 * The sacrum is the one segment that cannot be measured — the reference model
 * carries it as a single fused mesh with no posterior foramina — so the block
 * keeps the shape it had and is fitted into whatever span the ladder leaves.
 * It used to span 66 px from L5 to the coccyx; it now gets 70.
 */
const SACRAL_FIT = (COCCYX_Y - L5_Y) / 66;

export const SPINE = {
  /** T1..T12 spinous processes. */
  t: (n: number) => T1_Y + (n - 1) * T_STEP,
  /** L1..L5. */
  l: (n: number) => T12_Y + n * L_STEP,
  /** S1..S4 posterior sacral foramina. */
  s: (n: number) => L5_Y + (14 + (n - 1) * 12) * SACRAL_FIT,
  coccyx: COCCYX_Y,
} as const;

/**
 * The two paravertebral lines, 1.5 and 3 cun from the midline. Both are
 * bilateral in the body; the atlas draws the figure's LEFT one.
 *
 * SIDE CONVENTION: on the BACK view the observer stands behind the figure, so
 * the figure's left is the viewer's LEFT — the mirror image of the front view,
 * where the figure's left arm is drawn on the viewer's right. Back-view markers
 * for a channel that runs up the figure's left arm therefore sit at x < MID.
 */
export const BACK_LINE_1 = MID - 20;
export const BACK_LINE_2 = MID - 40;

/* --------------------------------------------------------------------------
 * LANDMARK-FIRST PLACEMENT
 *
 * Every point coordinate must be derived from a fixed, unambiguous surface
 * landmark plus a bone-cun (骨度分寸) distance — never estimated by eye. This
 * block defines those landmarks and the per-segment cun scales that GB/T
 * 12346-2021 measures against.
 *
 * WHY PER-SEGMENT SCALES: bone-cun is a proportional system. Each body segment
 * is divided into its own fixed number of units (forearm crease-to-crease = 12,
 * hip-to-popliteal = 19, xiphisternum-to-umbilicus = 8 …), so one cun is a
 * different number of pixels in each segment. Deriving each scale from the two
 * landmarks that bound its own segment means a point lands at its stated
 * distance from its own anchor even where the schematic's proportions differ
 * from a real body — which they do, because the figure is drawn to a 7.5-head
 * artistic canon, not to bone-cun.
 *
 * These are still layout coordinates on a schematic. Landmark anchoring makes
 * them internally consistent and reproducible; it does not make them validated
 * anatomical coordinates, and every placement stays `schematic_unvalidated`.
 * -------------------------------------------------------------------------- */

type Guide = readonly (readonly [number, number])[];

const dist = (a: readonly [number, number], b: readonly [number, number]) =>
  Math.hypot(b[0] - a[0], b[1] - a[1]);

/**
 * A point at `d` pixels along a limb centre-line, offset perpendicular by
 * `off` pixels. Positive `off` is to the RIGHT of the direction of travel
 * (which runs proximal → distal), so callers work in body terms, not pixels.
 */
function alongGuide(g: Guide, d: number, off = 0): { x: number; y: number } {
  let remaining = d;
  for (let i = 0; i < g.length - 1; i++) {
    const a = g[i]!;
    const b = g[i + 1]!;
    const len = dist(a, b);
    const last = i === g.length - 2;
    if (remaining <= len || last) {
      const t = len === 0 ? 0 : remaining / len;
      const ux = (b[0] - a[0]) / (len || 1);
      const uy = (b[1] - a[1]) / (len || 1);
      return {
        x: a[0] + (b[0] - a[0]) * t - uy * off,
        y: a[1] + (b[1] - a[1]) * t + ux * off,
      };
    }
    remaining -= len;
  }
  return { x: g[0]![0], y: g[0]![1] };
}

/**
 * Where the anterior axillary fold crosses the upper-arm guide, as a fraction
 * of the shoulder→elbow span. The guide starts at the shoulder JOINT, but the
 * standard's 9-cun upper arm is measured from the axillary FOLD, which sits
 * lower. Approximated once here so every upper-arm point inherits it.
 */
const AXILLA_FRACTION = 0.26;

function armGeometry(g: Guide) {
  const upper = dist(g[0]!, g[1]!);
  const fore = dist(g[1]!, g[2]!);
  return {
    /** Distance along the guide to each anchor. */
    axilla: upper * AXILLA_FRACTION,
    elbowCrease: upper,
    wristCrease: upper + fore,
    /** 腋前紋頭至肘橫紋 = 9 寸. */
    upperArmCun: (upper * (1 - AXILLA_FRACTION)) / 9,
    /** 肘橫紋至腕橫紋 = 12 寸. */
    forearmCun: fore / 12,
  };
}

function legGeometry(g: Guide) {
  const thigh = dist(g[0]!, g[1]!);
  const shank = dist(g[1]!, g[2]!);
  return {
    hip: 0,
    knee: thigh,
    ankle: thigh + shank,
    /** 股骨大轉子至膕橫紋 = 19 寸. */
    thighCun: thigh / 19,
    /** 膕橫紋至外踝尖 = 16 寸 (lateral / posterior channels). */
    shankLateralCun: shank / 16,
    /** 脛骨內側髁下方至內踝尖 = 13 寸 (medial channels). */
    shankMedialCun: shank / 13,
    /** 臀下橫紋至膕橫紋 = 14 寸 (posterior thigh, 承扶 → 委中). */
    posteriorThighCun: thigh / 14,
  };
}

const ARM_GEOM = {
  left: armGeometry(LIMB_GUIDES.armLeft),
  right: armGeometry(LIMB_GUIDES.armRight),
} as const;

const LEG_GEOM = {
  left: legGeometry(LIMB_GUIDES.legLeft),
  right: legGeometry(LIMB_GUIDES.legRight),
} as const;

/**
 * Fixed surface landmarks, as levels on the figure. Every trunk, head and
 * crease-adjacent point is measured from one of these.
 */
export const LANDMARKS = {
  /** 眉心 — between the brows; anchors 印堂 and the adjacent facial points. */
  glabella: LEVELS.eye - 15,
  /** 前髮際正中. 眉心至前髮際 = 3 寸. */
  frontHairline: hu(0.24),
  /** 胸骨上窩 (天突 level). */
  sternalNotch: 206,
  /** 乳頭 level — 4 寸 lateral, the 8-cun chest-width reference. */
  nippleLevel: LEVELS.nipple,
  nippleX: MID + 54,
  /** 胸劍聯合 (中庭 level), 9 寸 below the sternal notch. */
  xiphisternal: 291,
  /** 臍中 — the sole anchor for 天樞 and the surrounding abdominal points. */
  umbilicus: LEVELS.navel,
  /** 恥骨聯合上緣, 5 寸 below the umbilicus. The drawn crotch sits lower. */
  pubicSymphysis: LEVELS.crotch - 16,
  /** 肘橫紋 — the drawn cubital fossa sits on this line. */
  elbowCrease: LEVELS.elbow,
  /** 腕橫紋 / 腕掌側橫紋. */
  wristCrease: LEVELS.wrist,
  /** 髕底 (superior patellar border) and 髕尖 (inferior border, 犢鼻 level). */
  patellaSuperior: LEVELS.knee - 12,
  patellaInferior: LEVELS.knee + 6,
  /** 膕橫紋 — back view; 委中 sits at its midpoint. */
  poplitealCrease: LEVELS.knee,
  /** 踝尖. */
  malleolus: LEVELS.ankle,
  /** 後髮際正中 — back view. */
  backHairline: hu(0.98),
  /**
   * 第 7 頸椎棘突下.
   *
   * Anchored to the figure's own neck-base / trapezius junction rather than
   * extrapolated one step up the SPINE ladder. That ladder is calibrated from
   * T1 downward (navel ≈ L2, iliac crest ≈ L4); extending it upward lands on
   * the schematic's narrow drawn neck, where a point 2 寸 lateral — 肩中俞
   * SI15 — would float off the silhouette.
   */
  c7: LEVELS.neckBase + 9,
  /** 肩胛岡 (spine of the scapula) and the inferior angle, back view. */
  scapularSpine: hu(1.86),
  scapularInferiorAngle: hu(2.32),
  /** 腋後紋頭 — posterior axillary fold, back view. */
  posteriorAxillaryFold: hu(2.06),
  /** 臀下橫紋 — the gluteal fold. */
  glutealFold: LEVELS.crotch + 4,
  /** 尾骨端. */
  coccyxTip: 476,
  /** 骶管裂孔 — the sacral hiatus, just below S4; 腰俞 GV2 sits on it. */
  sacralHiatus: 468,
  /** 舌骨上緣 — above the laryngeal prominence; 廉泉 CV23 sits in that hollow. */
  hyoid: LEVELS.chin + 10,
  /** 頦唇溝 — the mentolabial groove below the lower lip; 承漿 CV24. */
  mentolabial: LEVELS.mouth + 11,
  /** 人中溝 — the philtrum, between the nose and the upper lip. */
  philtrum: LEVELS.nose + (LEVELS.mouth - LEVELS.nose) * 0.34,
  /** 上唇尖端 — the vermilion border at the midline; 兌端 GV27. */
  upperLip: LEVELS.mouth - 3,
  /** 耳屏 — tragus centre, per side. 聽宮 sits just in front of it. */
  tragus: { left: [MID + 42, hu(0.63)], right: [MID - 42, hu(0.63)] } as const,
  /**
   * 耳尖 / 耳垂 / 乳突 — auricle apex, lobe and mastoid.
   *
   * Placed against the DRAWN cranium and ear, not an idealised head: the ear is
   * drawn close to the skull here, so a mastoid set at a real head's width
   * lands behind the outline and every point derived from it — 翳風, 瘈脈,
   * 顱息 — floats off the figure.
   */
  earApex: { left: [MID + 40, hu(0.52)], right: [MID - 40, hu(0.52)] } as const,
  earLobe: { left: [MID + 44, hu(0.78)], right: [MID - 44, hu(0.78)] } as const,
  mastoid: { left: [MID + 34, hu(0.88)], right: [MID - 34, hu(0.88)] } as const,
  /** 眉梢 — lateral end of the eyebrow, where 絲竹空 sits. */
  browOuter: { left: [MID + 28, LEVELS.eye - 13], right: [MID - 28, LEVELS.eye - 13] } as const,
  /** 肩峰角 — acromial angle; 肩髎 sits behind and below 肩髃. */
  acromion: { left: [MID + 68, LEVELS.shoulder - 2], right: [MID - 68, LEVELS.shoulder - 2] } as const,
  /** 肩胛骨上角 — superior angle of the scapula, back view. */
  scapularSuperiorAngle: hu(1.72),
  /** 喉結 — the laryngeal prominence; 人迎 / 扶突 / 天窗 are level with it. */
  laryngealProminence: LEVELS.chin + 19,
  /**
   * Half-width of the drawn neck at the laryngeal level.
   *
   * The neck is the one region where the schematic is materially narrower than
   * a body: 扶突, 人迎, 天鼎 and 天窗 are separated by fractions of a cun across
   * a neck that is only ~1.5 cun of trunk width here. Offsetting them by the
   * neck's OWN width keeps their anterior→posterior order and keeps every one
   * on the figure, which trunk-cun offsets would not.
   */
  neckHalfWidth: 20,
} as const;

/** Bone-cun scales, one per segment, derived from the landmarks above. */
export const CUN = {
  /** 眉心至前髮際 = 3 寸. */
  head: (LANDMARKS.glabella - LANDMARKS.frontHairline) / 3,
  /** 胸骨上窩至胸劍聯合 = 9 寸. */
  chest: (LANDMARKS.xiphisternal - LANDMARKS.sternalNotch) / 9,
  /** 胸劍聯合至臍中 = 8 寸. */
  upperAbdomen: (LANDMARKS.umbilicus - LANDMARKS.xiphisternal) / 8,
  /** 臍中至恥骨聯合上緣 = 5 寸. */
  lowerAbdomen: (LANDMARKS.pubicSymphysis - LANDMARKS.umbilicus) / 5,
  /** 兩乳頭之間 = 8 寸, so half the chest is 4 寸. */
  trunkWidth: (LANDMARKS.nippleX - MID) / 4,
  armLeft: ARM_GEOM.left,
  armRight: ARM_GEOM.right,
  legLeft: LEG_GEOM.left,
  legRight: LEG_GEOM.right,
  /** Back view: the paravertebral lines fix 1.5 寸 = 20 px, so 3 寸 = 40 px. */
  back: 40 / 3,
  /** 臀下橫紋至膕橫紋 = 14 寸 (posterior thigh). */
  posteriorThigh: (LEVELS.knee - (LEVELS.crotch + 4)) / 14,
} as const;

/**
 * Rib interspaces, anchored on the nipple.
 *
 * GB/T defines the nipple level as 橫平第 4 肋間隙, so the nipple IS the
 * interspace-4 landmark; the others step off it by the standard 1.6-cun rib
 * spacing. This is how the chest points stay correct even though the figure
 * deliberately draws no nipple graphic (owner decision, 2026-08-06).
 */
export const ics = (n: number) => LANDMARKS.nippleLevel + (n - 4) * 1.6 * CUN.chest;

/** 鎖骨下緣 — the level 氣戶 ST13 sits on, one interspace above ICS1. */
export const CLAVICLE_LOWER = ics(0);

/**
 * A point n cun above the front hairline on the sagittal scalp line.
 *
 * The scalp arc is 12 cun front hairline → back hairline, so the vertex is at
 * 6. A true front-view projection of that arc would foreshorten the stations
 * into an unreadable cluster near the crown (BL4 and BL5 would land 0.7 px
 * apart), so the front view flattens the arc to an even ladder between two
 * landmarks — hairline and crown. Spacing stays proportional to the stated
 * cun; only the projection is schematic, and it is documented as such.
 */
export const scalpPoint = (cunAboveHairline: number, lateralCun = 0, side: 'left' | 'right' = 'left') => ({
  x: MID + (side === 'left' ? 1 : -1) * lateralCun * CUN.head,
  y: LANDMARKS.frontHairline - (cunAboveHairline / 6) * (LANDMARKS.frontHairline - CROWN),
});

/** 後髮際正中上 n 寸, on the back view. */
export const backScalp = (cunAboveHairline: number, lateralCun = 0, side: 'left' | 'right' = 'left') => ({
  x: MID + (side === 'left' ? -1 : 1) * lateralCun * CUN.back,
  y: LANDMARKS.backHairline - cunAboveHairline * CUN.head,
});

export type ArmAnchor = 'axilla' | 'elbowCrease' | 'wristCrease';

/**
 * A point on the arm, measured in cun from a crease.
 *
 * `cun` is signed along the limb: positive is DISTAL (toward the hand),
 * negative PROXIMAL. It is scaled by the segment the measurement belongs to —
 * upper arm above the elbow crease, forearm below it. `lateral` is in the same
 * segment's cun, positive AWAY from the body midline.
 */
export function armPoint(
  side: 'left' | 'right',
  from: ArmAnchor,
  cun: number,
  lateral = 0,
): { x: number; y: number } {
  const g = side === 'left' ? LIMB_GUIDES.armLeft : LIMB_GUIDES.armRight;
  const geom = ARM_GEOM[side];
  // The scale is the segment the measurement lies in: above the elbow crease
  // the 9-cun upper arm, below it the 12-cun forearm.
  const px =
    from === 'axilla' || (from === 'elbowCrease' && cun < 0)
      ? geom.upperArmCun
      : geom.forearmCun;
  // `alongGuide` offsets to the right of the proximal→distal direction, which
  // is toward -x on both limbs. Flip per side so `lateral` always means AWAY
  // from the body midline.
  const sign = side === 'left' ? -1 : 1;
  return alongGuide(g, geom[from] + cun * px, lateral * px * sign);
}

export type LegAnchor =
  | 'hip'
  | 'glutealFold'
  | 'patellaSuperior'
  | 'patellaInferior'
  | 'poplitealCrease'
  | 'malleolus';

/**
 * A point on the leg, measured in cun from a landmark. `cun` is positive
 * DISTAL. `scale` picks the 16-cun lateral/posterior measure or the 13-cun
 * medial one below the knee; above the knee both use the 19-cun thigh.
 */
export function legPoint(
  side: 'left' | 'right',
  from: LegAnchor,
  cun: number,
  lateral = 0,
  scale: 'lateral' | 'medial' = 'lateral',
): { x: number; y: number } {
  const g = side === 'left' ? LIMB_GUIDES.legLeft : LIMB_GUIDES.legRight;
  const geom = LEG_GEOM[side];
  // The patellar borders are levels on the drawn knee; convert them to distance
  // along the guide so a thigh point measured from 髕底 lands correctly.
  const along: Record<LegAnchor, number> = {
    hip: 0,
    // The guide starts level with the crotch, which is where the gluteal fold
    // crosses the back of the thigh.
    glutealFold: 0,
    patellaSuperior: geom.knee - (LEVELS.knee - LANDMARKS.patellaSuperior),
    patellaInferior: geom.knee + (LANDMARKS.patellaInferior - LEVELS.knee),
    poplitealCrease: geom.knee,
    malleolus: geom.ankle,
  };
  // Above the knee the 19-cun thigh; below it the 16-cun lateral/posterior or
  // 13-cun medial measure, whichever the channel is defined against.
  const shankCun = scale === 'medial' ? geom.shankMedialCun : geom.shankLateralCun;
  const px =
    from === 'glutealFold'
      ? geom.posteriorThighCun
      : from === 'hip' || from === 'patellaSuperior' || (from === 'patellaInferior' && cun < 0)
        ? geom.thighCun
        : shankCun;
  const sign = side === 'left' ? -1 : 1;
  return alongGuide(g, along[from] + cun * px, lateral * px * sign);
}

/** A trunk point: a landmark level (or cun from one) plus a lateral cun offset. */
export function trunkPoint(
  side: 'left' | 'right' | 'midline',
  level: number,
  lateralCun = 0,
): { x: number; y: number } {
  const sign = side === 'left' ? 1 : side === 'right' ? -1 : 0;
  return { x: MID + sign * lateralCun * CUN.trunkWidth, y: level };
}

/** 臍中上 n 寸 (n > 0) or 臍中下 n 寸 (n < 0), on the correct segment scale. */
export const fromUmbilicus = (cun: number) =>
  cun >= 0
    ? LANDMARKS.umbilicus - cun * CUN.upperAbdomen
    : LANDMARKS.umbilicus - cun * CUN.lowerAbdomen;

/** 胸骨上窩下 n 寸. */
export const belowSternalNotch = (cun: number) => LANDMARKS.sternalNotch + cun * CUN.chest;

/** Named surface landmarks the point data anchors to. */
export const FACE = {
  eyeR: [MID - 18, LEVELS.eye],
  eyeL: [MID + 18, LEVELS.eye],
  noseTip: [MID, LEVELS.nose],
  alaR: [MID - 12, LEVELS.nose + 2],
  alaL: [MID + 12, LEVELS.nose + 2],
  mouthCornerR: [MID - 16, LEVELS.mouth],
  mouthCornerL: [MID + 16, LEVELS.mouth],
  jawAngleR: [MID - 20, hu(1.19)],
  jawAngleL: [MID + 20, hu(1.19)],
  hairlineCornerR: [MID - 32, hu(0.24)],
  hairlineCornerL: [MID + 32, hu(0.24)],
} as const;

/* Cranium + jaw. Drawn as a path rather than an ellipse so the cheek and jaw
   give ST5–ST7 somewhere real to sit. */
const HEAD =
  `M${MID},${CROWN} C${MID + 24},${CROWN} ${MID + 41},${hu(0.16)} ${MID + 42},${hu(0.42)} ` +
  `C${MID + 43},${hu(0.62)} ${MID + 40},${hu(0.78)} ${MID + 34},${hu(0.9)} ` +
  `C${MID + 27},${hu(1.02)} ${MID + 14},${LEVELS.chin} ${MID},${LEVELS.chin} ` +
  `C${MID - 14},${LEVELS.chin} ${MID - 27},${hu(1.02)} ${MID - 34},${hu(0.9)} ` +
  `C${MID - 40},${hu(0.78)} ${MID - 43},${hu(0.62)} ${MID - 42},${hu(0.42)} ` +
  `C${MID - 41},${hu(0.16)} ${MID - 24},${CROWN} ${MID},${CROWN} Z`;

const NECK =
  `M${MID - 19},${hu(0.96)} C${MID - 20},${hu(1.12)} ${MID - 21},${hu(1.22)} ${MID - 24},${LEVELS.neckBase} ` +
  `L${MID + 24},${LEVELS.neckBase} C${MID + 21},${hu(1.22)} ${MID + 20},${hu(1.12)} ${MID + 19},${hu(0.96)} Z`;

/** Torso: trapezius, deltoid shelf, waist, hip flare. Mirrored about MID. */
const TORSO_LOOP: [number, number][] = [
  [MID - 18, LEVELS.neckBase - 6],
  [MID + 18, LEVELS.neckBase - 6],
  [MID + 44, hu(1.4)],
  [MID + 80, LEVELS.shoulder],
  [MID + 80, hu(1.85)],
  [MID + 76, hu(2.35)],
  [MID + 62, hu(2.75)],
  [MID + 54, LEVELS.navel],
  [MID + 64, hu(3.4)],
  [MID + 70, hu(3.72)],
  [MID + 42, LEVELS.crotch + 4],
  [MID, LEVELS.crotch + 12],
  [MID - 42, LEVELS.crotch + 4],
  [MID - 70, hu(3.72)],
  [MID - 64, hu(3.4)],
  [MID - 54, LEVELS.navel],
  [MID - 62, hu(2.75)],
  [MID - 76, hu(2.35)],
  [MID - 80, hu(1.85)],
  [MID - 80, LEVELS.shoulder],
  [MID - 44, hu(1.4)],
];

/* -------------------------------------------------------------------------- *
 * Extremity frames — origin at wrist/ankle, +y distal, +x lateral.
 * -------------------------------------------------------------------------- */

interface Frame {
  ox: number;
  oy: number;
  dx: number;
  dy: number;
  lx: number;
  ly: number;
}

function makeFrame(
  origin: readonly [number, number],
  towards: readonly [number, number],
  lateralSign: 1 | -1,
): Frame {
  const vx = towards[0] - origin[0];
  const vy = towards[1] - origin[1];
  const len = Math.hypot(vx, vy) || 1;
  const dx = vx / len;
  const dy = vy / len;
  return { ox: origin[0], oy: origin[1], dx, dy, lx: -dy * lateralSign, ly: dx * lateralSign };
}

const at = (f: Frame, lx: number, ly: number): [number, number] => [
  f.ox + f.dx * ly + f.lx * lx,
  f.oy + f.dy * ly + f.ly * lx,
];

const WRIST_R = LIMB_GUIDES.armRight[2];
const WRIST_L = LIMB_GUIDES.armLeft[2];
const ANKLE_R = LIMB_GUIDES.legRight[2];
const ANKLE_L = LIMB_GUIDES.legLeft[2];

const handFrames: Record<'left' | 'right', Frame> = {
  right: makeFrame(WRIST_R, [WRIST_R[0] - 8, WRIST_R[1] + 78], 1),
  left: makeFrame(WRIST_L, [WRIST_L[0] + 8, WRIST_L[1] + 78], -1),
};
const footFrames: Record<'left' | 'right', Frame> = {
  right: makeFrame(ANKLE_R, [ANKLE_R[0] - 20, ANKLE_R[1] + 46], 1),
  left: makeFrame(ANKLE_L, [ANKLE_L[0] + 20, ANKLE_L[1] + 46], -1),
};

/** Landmark → atlas coordinates. Drawing and point data share these numbers. */
export const handPoint = (side: 'left' | 'right', lx: number, ly: number) => {
  const [x, y] = at(handFrames[side], lx, ly);
  return { x, y };
};
export const footPoint = (side: 'left' | 'right', lx: number, ly: number) => {
  const [x, y] = at(footFrames[side], lx, ly);
  return { x, y };
};
/** Fractional position along a limb guide, offset laterally in px. */
export function alongLimb(
  guide: readonly (readonly [number, number])[],
  t: number,
  lateral = 0,
): { x: number; y: number } {
  const segs: number[] = [];
  let total = 0;
  for (let i = 0; i < guide.length - 1; i++) {
    const L = Math.hypot(guide[i + 1]![0] - guide[i]![0], guide[i + 1]![1] - guide[i]![1]);
    segs.push(L);
    total += L;
  }
  let want = Math.max(0, Math.min(1, t)) * total;
  for (let i = 0; i < segs.length; i++) {
    if (want <= segs[i]! || i === segs.length - 1) {
      const f = segs[i] ? want / segs[i]! : 0;
      const a = guide[i]!;
      const b = guide[i + 1]!;
      const dx = (b[0] - a[0]) / (segs[i] || 1);
      const dy = (b[1] - a[1]) / (segs[i] || 1);
      return { x: a[0] + (b[0] - a[0]) * f - dy * lateral, y: a[1] + (b[1] - a[1]) * f + dx * lateral };
    }
    want -= segs[i]!;
  }
  const last = guide[guide.length - 1]!;
  return { x: last[0], y: last[1] };
}

/** Hand: open palm, five distinctly spread digits. */
const PALM_LOOP: [number, number][] = [
  [9, 1], [14, 11], [16, 24], [14, 35], [7, 40], [0, 41],
  [-7, 39], [-13, 35], [-15, 23], [-12, 10], [-8, 1],
];
const DIGITS: { pts: [number, number][]; w: number[] }[] = [
  { pts: [[11, 10], [21, 23], [30, 36]], w: [6.4, 5.4, 4.4] }, // thumb, swung clear
  { pts: [[11, 36], [14, 53], [17, 70]], w: [5, 4.2, 3.5] }, // index
  { pts: [[3, 38], [4, 58], [5, 77]], w: [5.2, 4.3, 3.6] }, // middle
  { pts: [[-5, 37], [-7, 55], [-9, 72]], w: [5, 4.1, 3.4] }, // ring
  { pts: [[-12, 34], [-15, 48], [-19, 61]], w: [4.4, 3.6, 3] }, // little
];

/**
 * Foot seen from BEHIND.
 *
 * The back view was drawing the front view's foot — a dorsal splay with five
 * toes fanned at the viewer, which is what you see from above and in front,
 * never from behind. From behind the heel is the mass you see; the foot runs
 * away from you and only its lateral border and the outer toes clear it.
 *
 * The lateral border is kept where it already was, deliberately. 崑崙 BL60
 * through 至陰 BL67 and 丘墟 GB40 all sit on it, between lx 7 and 13 and ly 3
 * and 41, and they are the only nine points drawn over a foot on this view.
 * Shaping the heel around them means the redraw moves no coordinate — and
 * coordinates in this project come from a landmark and a bone-cun distance,
 * not from whatever a new outline happened to need.
 */
const POSTERIOR_FOOT_LOOP: [number, number][] = [
  [9, 0], [13, 10], [15, 20], [15, 30], [14, 38], [12, 44],
  [5, 45], [-1, 43], [-7, 38], [-11, 28], [-13, 18], [-11, 8], [-9, 0],
];

/**
 * All five toes from behind — foreshortened, not deleted.
 *
 * The first version drew only the outer two, on the reasoning that the rest
 * hide behind the heel. On screen that read as a stump: a foot with two stubby
 * digits looks deformed rather than turned away. It also broke the figure
 * spec, which requires articulated digits.
 *
 * Five short toes along the distal edge is the honest reading of a foot
 * pointing away from the viewer: each one is still there and still in order,
 * big toe medial, but they project a few units instead of a dozen because you
 * are looking down their length.
 */
const POSTERIOR_TOES: { pts: [number, number][]; w: number[] }[] = [
  { pts: [[-9, 37], [-9.5, 42]], w: [5.4, 4.6] },
  { pts: [[-4, 41], [-4, 46]], w: [3.6, 3.1] },
  { pts: [[1, 44], [1, 48.5]], w: [3.4, 2.9] },
  { pts: [[6.5, 44], [7, 48]], w: [3.2, 2.7] },
  { pts: [[12, 42], [13, 46]], w: [3, 2.5] },
];

/** Foot: sole plus five toes, big toe medial. */
const FOOT_LOOP: [number, number][] = [
  [8, 0], [11, 12], [13, 24], [14, 34], [9, 39], [0, 40],
  [-9, 39], [-13, 34], [-15, 24], [-11, 12], [-8, 0],
];
const TOES: { pts: [number, number][]; w: number[] }[] = [
  { pts: [[-10, 37], [-11, 49]], w: [6, 5.2] },
  { pts: [[-4, 39], [-4.5, 50]], w: [4, 3.4] },
  { pts: [[1.5, 39], [1.5, 48]], w: [3.7, 3.1] },
  { pts: [[6.5, 38], [7.5, 46]], w: [3.4, 2.9] },
  { pts: [[11, 35], [13, 42]], w: [3.1, 2.6] },
];

/** Distance from a point to a segment, in the extremity's local frame. */
function distToSeg(px: number, py: number, ax: number, ay: number, bx: number, by: number) {
  const dx = bx - ax;
  const dy = by - ay;
  const L2 = dx * dx + dy * dy || 1;
  const t = Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / L2));
  return Math.hypot(px - (ax + dx * t), py - (ay + dy * t));
}

function pointInLoop(px: number, py: number, loop: readonly (readonly [number, number])[]) {
  let inside = false;
  for (let i = 0, j = loop.length - 1; i < loop.length; j = i++) {
    const [xi, yi] = loop[i]!;
    const [xj, yj] = loop[j]!;
    if (yi > py !== yj > py && px < ((xj - xi) * (py - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

/**
 * Is a local (lx, ly) actually ON the drawn hand or foot?
 *
 * Used by the placement tests. Markers on the digits were previously written
 * past the fingertip, so they floated outside the silhouette; this makes that
 * an assertable property rather than something only the eye can catch.
 */
export function onExtremity(kind: 'hand' | 'foot', lx: number, ly: number): boolean {
  const loop = kind === 'hand' ? PALM_LOOP : FOOT_LOOP;
  if (pointInLoop(lx, ly, loop)) return true;
  const digits = kind === 'hand' ? DIGITS : TOES;
  return digits.some((d) => {
    for (let i = 0; i < d.pts.length - 1; i++) {
      const a = d.pts[i]!;
      const b = d.pts[i + 1]!;
      const w = Math.max(d.w[i]!, d.w[i + 1]!);
      if (distToSeg(lx, ly, a[0], a[1], b[0], b[1]) <= w) return true;
    }
    return false;
  });
}

function extremityShapes(
  frame: Frame,
  loop: [number, number][],
  digits: { pts: [number, number][]; w: number[] }[],
): FigureShape[] {
  const mapped = loop.map(([lx, ly]) => {
    const [x, y] = at(frame, lx, ly);
    return { x, y };
  });
  return [
    ...digits.map((d) => ({
      kind: 'path' as const,
      d: limbOutline(
        d.pts.map(([lx, ly]) => at(frame, lx, ly)),
        d.w,
      ),
    })),
    { kind: 'path', d: `${smoothPath(mapped)} Z` },
  ];
}

const ARM_WIDTHS = [21, 15, 11] as const;
const LEG_WIDTHS = [33, 22, 14] as const;

/**
 * The body, per view.
 *
 * The hands and feet used to live in a single shared array, so the back view
 * drew the front view's extremities and never turned them round. The hand's
 * silhouette is genuinely the same on both — turning the body and seeing the
 * other face cancel out, so a splayed hand with the thumb lateral reads as a
 * right palm or a left dorsum — and it keeps its shape here, gaining knuckles
 * rather than a mirror. The foot does not: from behind you see the heel.
 */
const figureCommonFor = (view: BodyViewId): FigureShape[] => [
  { kind: 'path', d: limbOutline(LIMB_GUIDES.armRight, ARM_WIDTHS) },
  { kind: 'path', d: limbOutline(LIMB_GUIDES.armLeft, ARM_WIDTHS) },
  ...extremityShapes(handFrames.right, PALM_LOOP, DIGITS),
  ...extremityShapes(handFrames.left, PALM_LOOP, DIGITS),
  { kind: 'path', d: limbOutline(LIMB_GUIDES.legRight, LEG_WIDTHS) },
  { kind: 'path', d: limbOutline(LIMB_GUIDES.legLeft, LEG_WIDTHS) },
  ...extremityShapes(
    footFrames.right,
    view === 'back' ? POSTERIOR_FOOT_LOOP : FOOT_LOOP,
    view === 'back' ? POSTERIOR_TOES : TOES,
  ),
  ...extremityShapes(
    footFrames.left,
    view === 'back' ? POSTERIOR_FOOT_LOOP : FOOT_LOOP,
    view === 'back' ? POSTERIOR_TOES : TOES,
  ),
  { kind: 'path', d: NECK },
  {
    kind: 'path',
    d: `${smoothPath(
      TORSO_LOOP.concat([TORSO_LOOP[0]!]).map(([x, y]) => ({ x, y })),
      0.5,
    )} Z`,
  },
  { kind: 'path', d: HEAD },
];

/** A stroke described in an extremity's own local frame. */
const localStroke = (
  f: Frame,
  pts: [number, number][],
  strokeWidth = 1.6,
): FigureShape => ({
  kind: 'stroke',
  d: smoothPath(
    pts.map(([lx, ly]) => {
      const [x, y] = at(f, lx, ly);
      return { x, y };
    }),
  ),
  strokeWidth,
});

/**
 * What tells the back of a hand from a palm, and a heel from a dorsum.
 *
 * The hand keeps its outline and gains knuckles: the row of
 * metacarpophalangeal joints where the fingers start, and the metacarpal
 * shafts running back to the wrist. A palm has neither, so their presence is
 * the whole signal that this is the other face.
 *
 * The foot gains the heel's own curve and the Achilles above it.
 */
const posteriorExtremityDetail: FigureShape[] = (['right', 'left'] as const).flatMap((side) => [
  // Knuckle row, bowed the way the metacarpal heads actually sit.
  localStroke(handFrames[side], [[-12, 33], [-4, 36.5], [4, 37], [11, 34.5]], 1.5),
  // Three metacarpal shafts. Not five: the drawn hand is 30px across and five
  // lines at this scale read as hatching rather than as bones.
  localStroke(handFrames[side], [[8, 20], [10, 32]], 1.2),
  localStroke(handFrames[side], [[1, 21], [2.5, 34]], 1.2),
  localStroke(handFrames[side], [[-6, 20], [-6, 33]], 1.2),
  // Heel curve, and the Achilles running up out of it into the calf.
  localStroke(footFrames[side], [[-9, 14], [0, 18], [9, 14]], 1.6),
  localStroke(footFrames[side], [[0, -14], [0.5, -6], [0, 2]], 1.8),
]);

/** Ears — drawn after the head so they read as attached, not floating. */
/* --------------------------------------------------------------------------
 * EXTREMITY DETAIL VIEWS
 *
 * The hands and feet carry the densest cluster of points on the whole figure —
 * 井穴, 滎穴, 輸穴 and the web-space points all sit within a few millimetres of
 * each other. At whole-body zoom their labels cannot all be drawn, so each
 * extremity gets its own zoomed detail view.
 *
 * The box below is computed from the SAME loop and digit geometry that draws
 * the hand or foot, so the detail view can never disagree with the main model:
 * it is a second camera on one drawing, not a second drawing.
 * -------------------------------------------------------------------------- */

export interface ExtremityRegion {
  id: 'hand-left' | 'hand-right' | 'foot-left' | 'foot-right';
  kind: 'hand' | 'foot';
  side: 'left' | 'right';
  labelZhHant: string;
  labelEn: string;
  /** Bounding box in atlas user units, padded for context. */
  box: { x: number; y: number; w: number; h: number };
  /** Centre of the hotspot the learner taps on the whole-body figure. */
  hotspot: { x: number; y: number; r: number };
}

function extremityBox(frame: Frame, kind: 'hand' | 'foot') {
  /*
   * The UNION of both views' geometry, not the front's alone.
   *
   * The posterior foot reaches further down its lateral border than the dorsal
   * one does, and this box drives the detail camera and the hotspot. Sizing it
   * from one view would crop the other — and cropping is the failure this box
   * was written to avoid.
   */
  const loop =
    kind === 'hand' ? PALM_LOOP : ([...FOOT_LOOP, ...POSTERIOR_FOOT_LOOP] as [number, number][]);
  const digits = kind === 'hand' ? DIGITS : [...TOES, ...POSTERIOR_TOES];
  const locals: [number, number][] = [
    ...loop,
    ...digits.flatMap((d) =>
      d.pts.map((pt, i): [number, number] => [pt[0], pt[1] + (d.w[i] ?? 0)]),
    ),
    ...digits.flatMap((d) => d.pts.map((pt, i): [number, number] => [pt[0] + (d.w[i] ?? 0), pt[1]])),
    ...digits.flatMap((d) => d.pts.map((pt, i): [number, number] => [pt[0] - (d.w[i] ?? 0), pt[1]])),
  ];
  const pts = locals.map(([lx, ly]) => at(frame, lx, ly));
  const xs = pts.map((q) => q[0]);
  const ys = pts.map((q) => q[1]);
  // Padding for the shape, plus a wider allowance on +x where the detail view
  // draws its labels — without it the outermost 井穴 label (少商, 至陰) is
  // clipped by the viewBox edge.
  const pad = 10;
  const labelRoom = 30;
  const x = Math.min(...xs) - pad;
  const y = Math.min(...ys) - pad;
  return {
    box: { x, y, w: Math.max(...xs) - x + pad + labelRoom, h: Math.max(...ys) - y + pad },
    centre: at(frame, 0, kind === 'hand' ? 30 : 24),
  };
}

const extremity = (
  id: ExtremityRegion['id'],
  kind: 'hand' | 'foot',
  side: 'left' | 'right',
  labelZhHant: string,
  labelEn: string,
): ExtremityRegion => {
  const frame = kind === 'hand' ? handFrames[side] : footFrames[side];
  const { box, centre } = extremityBox(frame, kind);
  return {
    id,
    kind,
    side,
    labelZhHant,
    labelEn,
    box,
    hotspot: { x: centre[0], y: centre[1], r: kind === 'hand' ? 30 : 24 },
  };
};

/**
 * SIDE NAMING: labels describe the FIGURE's own left and right, which is what a
 * learner needs. On the back view the figure's left falls on the viewer's left;
 * on the front view it falls on the viewer's right.
 */
export const EXTREMITIES: ExtremityRegion[] = [
  extremity('hand-left', 'hand', 'left', '左手', 'Left hand'),
  extremity('hand-right', 'hand', 'right', '右手', 'Right hand'),
  extremity('foot-left', 'foot', 'left', '左足', 'Left foot'),
  extremity('foot-right', 'foot', 'right', '右足', 'Right foot'),
];

/** Is an atlas coordinate inside this extremity's detail box? */
export const inExtremity = (r: ExtremityRegion, x: number, y: number) =>
  x >= r.box.x && x <= r.box.x + r.box.w && y >= r.box.y && y <= r.box.y + r.box.h;

const EARS: FigureShape[] = [
  {
    kind: 'path',
    d: `M${MID + 40},${hu(0.5)} C${MID + 52},${hu(0.48)} ${MID + 54},${hu(0.66)} ${MID + 46},${hu(0.78)} ` +
      `C${MID + 43},${hu(0.83)} ${MID + 40},${hu(0.82)} ${MID + 39},${hu(0.78)} Z`,
  },
  {
    kind: 'path',
    d: `M${MID - 40},${hu(0.5)} C${MID - 52},${hu(0.48)} ${MID - 54},${hu(0.66)} ${MID - 46},${hu(0.78)} ` +
      `C${MID - 43},${hu(0.83)} ${MID - 40},${hu(0.82)} ${MID - 39},${hu(0.78)} Z`,
  },
];

/**
 * Front-view surface detail. Facial features and joint contours are landmark
 * references, not decoration — the learner locates ST1–ST8 against the eye,
 * nose, mouth and jaw, and elbow/knee points against these creases.
 */
const frontOnly: FigureShape[] = [
  // Eyes, nose, mouth — minimal, calm, no expression.
  {
    kind: 'stroke',
    d: `M${MID - 27},${LEVELS.eye} Q${MID - 18},${LEVELS.eye - 6} ${MID - 9},${LEVELS.eye} ` +
      `Q${MID - 18},${LEVELS.eye + 4} ${MID - 27},${LEVELS.eye}`,
    strokeWidth: 2,
  },
  {
    kind: 'stroke',
    d: `M${MID + 9},${LEVELS.eye} Q${MID + 18},${LEVELS.eye - 6} ${MID + 27},${LEVELS.eye} ` +
      `Q${MID + 18},${LEVELS.eye + 4} ${MID + 9},${LEVELS.eye}`,
    strokeWidth: 2,
  },
  // Brows, which also give 頭維 / 陽白-class points a reference line.
  { kind: 'stroke', d: `M${MID - 28},${LEVELS.eye - 13} Q${MID - 18},${LEVELS.eye - 17} ${MID - 8},${LEVELS.eye - 13}`, strokeWidth: 1.8 },
  { kind: 'stroke', d: `M${MID + 8},${LEVELS.eye - 13} Q${MID + 18},${LEVELS.eye - 17} ${MID + 28},${LEVELS.eye - 13}`, strokeWidth: 1.8 },
  { kind: 'stroke', d: `M${MID},${LEVELS.eye + 6} L${MID},${LEVELS.nose - 4} Q${MID},${LEVELS.nose} ${MID + 6},${LEVELS.nose + 1}`, strokeWidth: 2 },
  { kind: 'stroke', d: `M${MID - 12},${LEVELS.nose + 2} Q${MID},${LEVELS.nose + 6} ${MID + 12},${LEVELS.nose + 2}`, strokeWidth: 1.8 },
  { kind: 'stroke', d: `M${MID - 15},${LEVELS.mouth} Q${MID},${LEVELS.mouth + 5} ${MID + 15},${LEVELS.mouth}`, strokeWidth: 2.2 },
  // Clavicles, sternum, navel.
  //
  // DELIBERATELY ABSENT: nipple graphics. Owner decision (2026-08-06) — no
  // visual nipple markers on the torso, to keep a general-audience educational
  // app clean. The chest points depend on that landmark for accuracy, so it is
  // carried in TEXT instead: every ST13–ST18 and SP17–SP21 location states its
  // intercostal space, and a test in placement.test.ts enforces that.
  { kind: 'stroke', d: `M${MID - 46},${hu(1.62)} Q${MID - 22},${hu(1.7)} ${MID},${hu(1.68)} Q${MID + 22},${hu(1.7)} ${MID + 46},${hu(1.62)}`, strokeWidth: 2 },
  { kind: 'stroke', d: `M${MID},${hu(1.78)} L${MID},${hu(2.5)}`, strokeWidth: 1.6 },
  { kind: 'stroke', d: `M${MID - 4},${LEVELS.navel} Q${MID},${LEVELS.navel + 5} ${MID + 4},${LEVELS.navel}`, strokeWidth: 2 },
  // Cubital fossa (elbow crease) and patella outline.
  { kind: 'stroke', d: `M${LIMB_GUIDES.armRight[1][0] - 11},${LEVELS.elbow} Q${LIMB_GUIDES.armRight[1][0]},${LEVELS.elbow + 6} ${LIMB_GUIDES.armRight[1][0] + 11},${LEVELS.elbow}`, strokeWidth: 1.8 },
  { kind: 'stroke', d: `M${LIMB_GUIDES.armLeft[1][0] - 11},${LEVELS.elbow} Q${LIMB_GUIDES.armLeft[1][0]},${LEVELS.elbow + 6} ${LIMB_GUIDES.armLeft[1][0] + 11},${LEVELS.elbow}`, strokeWidth: 1.8 },
  { kind: 'stroke', d: `M${LIMB_GUIDES.legRight[1][0] - 13},${LEVELS.knee - 12} Q${LIMB_GUIDES.legRight[1][0]},${LEVELS.knee + 12} ${LIMB_GUIDES.legRight[1][0] + 13},${LEVELS.knee - 12}`, strokeWidth: 1.8 },
  { kind: 'stroke', d: `M${LIMB_GUIDES.legLeft[1][0] - 13},${LEVELS.knee - 12} Q${LIMB_GUIDES.legLeft[1][0]},${LEVELS.knee + 12} ${LIMB_GUIDES.legLeft[1][0] + 13},${LEVELS.knee - 12}`, strokeWidth: 1.8 },
];

/** Back-view detail: occiput, spine, scapulae, gluteal fold, joint creases. */
const backOnly: FigureShape[] = [
  { kind: 'stroke', d: `M${MID - 26},${hu(0.86)} Q${MID},${hu(0.94)} ${MID + 26},${hu(0.86)}`, strokeWidth: 2 },
  { kind: 'stroke', d: `M${MID},${LEVELS.neckBase} C${MID + 2},${hu(2.2)} ${MID - 2},${hu(3.2)} ${MID},${LEVELS.crotch - 6}`, strokeWidth: 2.2 },
  { kind: 'stroke', d: `M${MID - 52},${hu(1.72)} Q${MID - 34},${hu(2.02)} ${MID - 22},${hu(2.2)}`, strokeWidth: 1.8 },
  { kind: 'stroke', d: `M${MID + 52},${hu(1.72)} Q${MID + 34},${hu(2.02)} ${MID + 22},${hu(2.2)}`, strokeWidth: 1.8 },
  { kind: 'stroke', d: `M${MID - 40},${hu(3.62)} Q${MID},${hu(3.72)} ${MID + 40},${hu(3.62)}`, strokeWidth: 1.8 },
  { kind: 'stroke', d: `M${MID - 34},${LEVELS.crotch + 2} Q${MID - 20},${hu(4.12)} ${MID - 8},${LEVELS.crotch + 4}`, strokeWidth: 1.6 },
  { kind: 'stroke', d: `M${MID + 34},${LEVELS.crotch + 2} Q${MID + 20},${hu(4.12)} ${MID + 8},${LEVELS.crotch + 4}`, strokeWidth: 1.6 },
  { kind: 'stroke', d: `M${LIMB_GUIDES.legRight[1][0] - 12},${LEVELS.knee} Q${LIMB_GUIDES.legRight[1][0]},${LEVELS.knee - 5} ${LIMB_GUIDES.legRight[1][0] + 12},${LEVELS.knee}`, strokeWidth: 1.8 },
  { kind: 'stroke', d: `M${LIMB_GUIDES.legLeft[1][0] - 12},${LEVELS.knee} Q${LIMB_GUIDES.legLeft[1][0]},${LEVELS.knee - 5} ${LIMB_GUIDES.legLeft[1][0] + 12},${LEVELS.knee}`, strokeWidth: 1.8 },
];

/** Ear detail — a visible landmark, not decoration (下關 sits just in front). */
const EAR_DETAIL: FigureShape[] = [
  { kind: 'stroke', d: `M${MID + 41},${hu(0.54)} C${MID + 49},${hu(0.56)} ${MID + 49},${hu(0.7)} ${MID + 43},${hu(0.76)}`, strokeWidth: 1.8 },
  { kind: 'stroke', d: `M${MID - 41},${hu(0.54)} C${MID - 49},${hu(0.56)} ${MID - 49},${hu(0.7)} ${MID - 43},${hu(0.76)}`, strokeWidth: 1.8 },
];

export const figureShapes: Record<BodyViewId, FigureShape[]> = {
  front: [...figureCommonFor('front'), ...EARS, ...EAR_DETAIL, ...frontOnly],
  back: [
    ...figureCommonFor('back'),
    ...EARS,
    ...EAR_DETAIL,
    ...backOnly,
    ...posteriorExtremityDetail,
  ],
};

/**
 * The rectangle the drawn figure actually occupies, per view.
 *
 * Derived by scanning the shapes' own numbers rather than measured in a
 * browser or written down: a detail frame that extends past the figure is
 * showing empty background, and the head frame was spending a quarter of its
 * height on the blank space above the skull.
 *
 * Curve control points are included, so the box can be marginally larger than
 * the true silhouette. That is the safe direction — it never crops anything.
 */
const boundsCache = new Map<BodyViewId, { x: number; y: number; w: number; h: number }>();

export function figureBounds(view: BodyViewId) {
  const hit = boundsCache.get(view);
  if (hit) return hit;

  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  const see = (x: number, y: number) => {
    if (!Number.isFinite(x) || !Number.isFinite(y)) return;
    minX = Math.min(minX, x);
    minY = Math.min(minY, y);
    maxX = Math.max(maxX, x);
    maxY = Math.max(maxY, y);
  };

  for (const s of figureShapes[view]) {
    if (s.kind === 'circle') {
      const { cx = 0, cy = 0, r = 0 } = s;
      see(cx - r, cy - r);
      see(cx + r, cy + r);
      continue;
    }
    // Path data is "C x,y x,y x,y" style throughout this file: every number is
    // a coordinate, alternating x and y.
    const nums = (s.d ?? '').match(/-?\d+(\.\d+)?/g);
    if (!nums) continue;
    for (let i = 0; i + 1 < nums.length; i += 2) {
      see(Number(nums[i]), Number(nums[i + 1]));
    }
  }

  const box = { x: minX, y: minY, w: maxX - minX, h: maxY - minY };
  boundsCache.set(view, box);
  return box;
}

/**
 * Dash pattern per line style, at ATLAS scale. Channels are never distinguished
 * by colour alone, so anything drawing a route at this size — the atlas itself,
 * the topic-card avatar — takes its dasharray from here rather than keeping its
 * own copy. The legend swatch has its own smaller-scale vocabulary in
 * `LineSwatch`, tuned for a 26px line.
 */
export const MERIDIAN_DASH: Record<string, string | undefined> = {
  solid: undefined,
  dashed: '7 5',
  dotted: '0.5 6',
  dashdot: '9 4 1.5 4',
  longdash: '14 6',
  shortdash: '4 4',
  dashdotdot: '10 4 1.5 4 1.5 4',
  longdashdot: '18 5 2 5',
  finedash: '3 6',
  doubledash: '12 4 4 4',
  longdashdotdot: '16 4 1.5 4 1.5 4',
  sparsedot: '1 8',
  railroad: '2 3 9 3',
  longsolid: '26 5',
};

/**
 * Catmull-Rom → cubic Bézier. Used to draw a meridian route through its own
 * ordered point placements, so the diagram is derived from route data rather
 * than hand-drawn separately from it.
 */
export function smoothPath(points: { x: number; y: number }[], tension = 0.5): string {
  if (points.length === 0) return '';
  const first = points[0]!;
  if (points.length === 1) return `M${first.x.toFixed(2)},${first.y.toFixed(2)}`;

  let d = `M${first.x.toFixed(2)},${first.y.toFixed(2)}`;
  for (let i = 0; i < points.length - 1; i++) {
    const p0 = points[Math.max(0, i - 1)]!;
    const p1 = points[i]!;
    const p2 = points[i + 1]!;
    const p3 = points[Math.min(points.length - 1, i + 2)]!;
    const c1x = p1.x + ((p2.x - p0.x) / 6) * tension;
    const c1y = p1.y + ((p2.y - p0.y) / 6) * tension;
    const c2x = p2.x - ((p3.x - p1.x) / 6) * tension;
    const c2y = p2.y - ((p3.y - p1.y) / 6) * tension;
    d += ` C${c1x.toFixed(2)},${c1y.toFixed(2)} ${c2x.toFixed(2)},${c2y.toFixed(2)} ${p2.x.toFixed(2)},${p2.y.toFixed(2)}`;
  }
  return d;
}
